__author__ = 'mikhail91'

from setuptools import setup, find_packages

setup(
    name='data_popularity_api',
    version='0.1',
    url='',
    author='Mikhail Hushchyn',
    author_email='mikhail91@yandex-team.ru',
    packages=find_packages(),
    description='',
    install_requires=[
        "docutils==0.12",
        "Flask==0.10.1",
        "Flask-RESTful==0.3.2",
        "ipython==3.0.0",
        "itsdangerous==0.24",
        "Jinja2==2.7.3",
        "jsonschema==2.4.0",
        "kernel-regression==1.0",
        "MarkupSafe==0.23",
        "matplotlib==1.4.3",
        "mistune==0.5.1",
        "mock==1.0.1",
        "nose==1.3.4",
        "numexpr==2.4",
        "numpy==1.9.2",
        "numpydoc==0.5",
        "openpyxl==1.8.6",
        "pandas==0.14.0",
        "plotly==1.2.3",
        "ptyprocess==0.4",
        "pycurl==7.19.5.1",
        "Pygments==2.0.2",
        "pyparsing==2.0.3",
        "python-dateutil==2.4.1",
        "pytz==2014.10",
        "pyzmq==14.5.0",
        "rep==0.5.0",
        "requests==2.5.3",
        "scikit-learn==0.15.2",
        "scipy==0.15.1",
        "six==1.9.0",
        "snowballstemmer==1.2.0",
        "Sphinx==1.3",
        "sphinx-rtd-theme==0.1.7",
        "terminado==0.5",
        "tornado==4.1",
        "Werkzeug==0.10.1",
        "xlrd==0.9.3",
        ],
    include_package_data=True,
    py_modules = ['dp_api']
)
